blank_issues_enabled: false
contact_links:
  - name: Citra Discord
    url:
    about: If you are experiencing an issue with CitraVR, and you need tech support, or if you have a general question, try asking in the [CitraVR Discord](https://github.com/amwatson/CitraVR/blob/master/README.md#discord). Piracy is not allowed.
